# Site settings
title: MAGINVE
email: admin@maginve.com
description: >
  A collection of high-quality HD, Full HD, and 4K wallpapers featuring nature landscapes, mountains, forests, beaches, sunsets, city views, and aesthetic designs.

url: "https://maginve.com"
baseurl: "/"

timezone: Asia/Jakarta

future: false

default-image: logo.jpg
logo: logo.jpg

built-by: Maginve

copyright:
  name: Maginve
  link: "https://maginve.com"

markdown: kramdown
permalink: /:title/

paginate: 12
paginate_path: /page:num/

include:
  - _pages

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap